[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
fancy-regex = "0.16.2"
tokio = { version = "1.48.0", features = ["macros", "rt", "rt-multi-thread"] }

[dev-dependencies]
criterion = { version = "0.8.0", features = ["html_reports", "async", "async_tokio"] }

[[bench]]
name="benches"
harness=false
