#!/usr/bin/env bash
set -e

./build &> /dev/null

run () {
	echo -n "Zig: "
	./zig/zig-out/bin/"$1" input/"$1".txt
	du -h ./zig/zig-out/bin/"$1"
	
	echo -n "Rust: "
	./rust/target/release/"$1" input/"$1".txt
	du -h ./rust/target/release/"$1"
}

if [[ $# == 1 ]]; then
	run $1
	exit 0
fi

for file in input/*; do
  if [ -f "$file" ]; then
	  day=${file:6:-4}
	  run $day
	  echo "---------------------------------------------------------------------"
  fi
done

